-------------------------------------------------------------------------------
Test set: models.dao.Sql20MenWearDaoTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.5 sec <<< FAILURE! - in models.dao.Sql20MenWearDaoTest
models.dao.Sql20MenWearDaoTest  Time elapsed: 0.5 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: no pg_hba.conf entry for host "41.84.152.6", user "dymqwdieiyxasa", database "d7dmvoatoj65", SSL off
	at models.dao.Sql20MenWearDaoTest.setUp(Sql20MenWearDaoTest.java:26)
Caused by: org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "41.84.152.6", user "dymqwdieiyxasa", database "d7dmvoatoj65", SSL off
	at models.dao.Sql20MenWearDaoTest.setUp(Sql20MenWearDaoTest.java:26)

models.dao.Sql20MenWearDaoTest  Time elapsed: 0.5 sec  <<< ERROR!
java.lang.NullPointerException
	at models.dao.Sql20MenWearDaoTest.shutDown(Sql20MenWearDaoTest.java:37)

